### ISSUE TITLE
Turning off notifications not working

### ISSUE THREAD

**Issue by meltuhamy** [meltuhamy/belfastsalah#3]
I got notifications even though I turned them off

**Comment by meltuhamy** [comment]
It crashes because of invalid ids :( 

```
E/AndroidRuntime(10801): Process: com.meltuhamy.belfastsalah, PID: 10801
E/AndroidRuntime(10801): java.lang.NumberFormatException: Invalid int: "1426622400000"
E/AndroidRuntime(10801):    at java.lang.Integer.invalidInt(Integer.java:138)
E/AndroidRuntime(10801):    at java.lang.Integer.parse(Integer.java:413)
E/AndroidRuntime(10801):    at java.lang.Integer.parseInt(Integer.java:367)
E/AndroidRuntime(10801):    at java.lang.Integer.parseInt(Integer.java:334)
E/AndroidRuntime(10801):    at de.appplant.cordova.plugin.notification.Manager.getIds(Manager.java:197)
E/AndroidRuntime(10801):    at de.appplant.cordova.plugin.notification.Manager.getAll(Manager.java:246)
E/AndroidRuntime(10801):    at de.appplant.cordova.plugin.notification.Manager.getIdsByType(Manager.java:210)
E/AndroidRuntime(10801):    at de.appplant.cordova.plugin.localnotification.LocalNotification.getScheduledIds(LocalNotification.java:352)
E/AndroidRuntime(10801):    at de.appplant.cordova.plugin.localnotification.LocalNotification.access$1000(LocalNotification.java:48)
E/AndroidRuntime(10801):    at de.appplant.cordova.plugin.localnotification.LocalNotification$1.run(LocalNotification.java:172)
E/AndroidRuntime(10801):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(10801):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(10801):    at java.lang.Thread.run(Thread.java:818)
W/ActivityManager( 1221):   Force finishing activity com.meltuhamy.belfastsalah/.MainActivity
```

Solution: use better ids and not a timestamp.
